### ISSUE TITLE
Issues converting ABC notation to midi file

### ISSUE THREAD

**Issue by timtensor** [olaviinha/MusicWithChatGPT#2]
Hi, first of all great work and interesting workflow you have mentioned here. I have a question. I tried to download the midi file from .abc to .midi notebook but it resulted in an error . The .abc notation is here

`M:4/4
L:1/16
K:Gm
G,4 | G,4 | G,4 | G,4 |
G,4 | G,4 | G,4 | G,4 |
|: B,2B,2B,2B,2 G,2G,2G,2G,2 | B,2B,2B,2B,2 G,2G,2G,2G,2 |
B,2B,2B,2B,2 G,2G,2G,2G,2 | B,2B,2B,2B,2 G,2G,2G,2G,2 :|`
However it lead to the following issue - 
```
2023-04-09 00:12:09 No song title found, using: nixman
4.84 January 20 2023 abc2midi
Error in line-char 8-0 : No tune processed. Possible missing X: field

2023-04-09 00:12:10 Error saving MIDI.
```
Do you know why it happened so ?

**Comment by olaviinha** [comment]
Hmm I assume that contained line breaks. It seems to be missing some fields, as also indicated by the error. ChatGPT does mistakes sometimes, but it's also pretty good at fixing its own errors: just say that you tried to convert it to MIDI but got the following error: <paste error here> – very likely ChatGPT will give you a fixed version.

I just asked an ABC notation example with a simple melody and got this (note more fields):
```
X:1
T:Twinkle Twinkle Little Star
M:4/4
L:1/4
Q:1/4=120
K:C
G2 G2 A2 A2 | B2 B2 G2 | 
F2 F2 E2 E2 | D2 D2 C2 |
G2 G2 F2 F2 | E2 E2 D2 |
G2 G2 F2 F2 | E2 E2 D2 |
G2 G2 A2 A2 | B2 B2 G2 |
F2 F2 E2 E2 | D2 D2 C2 |
```

**Comment by timtensor** [comment]
I tried it again but the it could not download as midi file. So the ABC notation i was using was 
```
X:1
M:4/4
L:1/16
K:Gm
G,4 | G,4 | G,4 | G,4 |
G,4 | G,4 | G,4 | G,4 |
|: B,2B,2B,2B,2 G,2G,2G,2G,2 | B,2B,2B,2B,2 G,2G,2G,2G,2 |
B,2B,2B,2B,2 G,2G,2G,2G,2 | B,2B,2B,2B,2 G,2G,2G,2G,2 :|
```

i get the following 
2023-04-11 23:37:59 No song title found, using: noldeb
4.84 January 20 2023 abc2midi
```
voice mapping:
  1   
writing MIDI file /content/tmp/noldebmid
Warning in line-char 5-10 : Track 0 Bar 1 has 1 time units while the time signature has 4
Warning in line-char 5-16 : Track 0 Bar 2 has 1 time units while the time signature has 4
Warning in line-char 5-22 : Track 0 Bar 3 has 1 time units while the time signature has 4
Warning in line-char 6-4 : Track 0 Bar 4 has 1 time units while the time signature has 4
Warning in line-char 6-10 : Track 0 Bar 5 has 1 time units while the time signature has 4
Warning in line-char 6-16 : Track 0 Bar 6 has 1 time units while the time signature has 4
Warning in line-char 6-22 : Track 0 Bar 7 has 1 time units while the time signature has 4

2023-04-11 23:37:59 MIDI saved as noldebmid
2023-04-11 23:37:59 Downloading...
```
However the downloaded file doesnt have .midi extension . I am wondering why so ?

**Comment by olaviinha** [comment]
It was because of a typo: `file_out = dir_tmp+uniq_id+'mid'` (full stop missing between filename and its extension)

Usually the ABC notation from ChatGPT has a title, in which case the file is named a little differently. Anyway this has been fixed now!
