### ISSUE TITLE
How to Start it?

### ISSUE THREAD

**Issue by Minimalistic09** [olaviinha/MusicWithChatGPT#3]
Hello, how i can start this code in cmd?
i have try with ./ezchords (notes) but not work

thank you!

**Comment by olaviinha** [comment]
I don't know, that's why I make notebooks. What are you trying to do?

**Comment by ZeerohAura** [comment]
> I don't know, that's why I make notebooks. What are you trying to do?

I think what they are asking is what's the step by step instructions
can you record a video showing everything you click and type?
From setting it up, how to open chords2midi in powershell or python and how to actually use the features

for me I keep getting random errors or things wont download

**Comment by olaviinha** [comment]
You can't run it in PowerShell or Python without a [Jupyter environment](https://jupyter.org). That' why it's in Google Colab, which is a hosted runtime.

**Comment by olaviinha** [comment]
These solutions are made for Google Colab, which is a hosted runtime. You can run them locally by using a [Jupyter envirnoment](https://jupyter.org/) but unfortunately I am unable to provide support for that.

Here is a video for chords2midi:

https://user-images.githubusercontent.com/50331907/233773899-e9b6fd42-21b0-4503-bf01-9e2b3ae72ac7.mp4

**Comment by ZeerohAura** [comment]
Yoo! Bless thank you that's amazing!
